name: Add Dates to New Resources

on:
  push:
    branches:
      - main
    paths:
      - 'README.md'

jobs:
  add-dates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Add dates to new resources
        run: node scripts/add-dates.js

      - name: Commit changes (if any)
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Add dates to new resources"
          git push
